# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dc4aa0c5f9b36efce8e3aaccd9b5f48f43b633b630a6551d6212d5fea0227729e0ea5aca752caa303af7559914fdfa3a496827363de6139750d23276afce6ce

test:
  secret_key_base: 3ee6db6d6b5ddf9c2d65ddb8dffc2d075aa7dd50893bef9a25a9e77551dafadad5043d333f94db274c5abbe6935a15f908c39c290f1008ce17afa9346f9e4042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
